# serverless.yml

service: security

provider:
  name: aws
  stage: dev
  region: us-east-1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    environment:
      PORT: 5000
      senderEmail: samranvirk44@gmail.com
      emailPass: hittler1950
      superAdminEmail: samranvirk44@gmail.com